Update chain.json
archway-network/networks pull request #172
Opened 2023-07-12 07:53 UTC by nochanc3

Added MMS team endpoints and seed node

2023-08-16 11:56 UTC, jlehtimaki requested changes
resolve the conflicts

2023-08-16 14:27 UTC, nochanc3 commented
> resolve the conflicts

Resolved

2023-09-27 09:10 UTC, jlehtimaki requested changes

2023-09-27 09:10 UTC, jlehtimaki commented on archway-1/chain.json
> +        "address": "https://grpc-archway.mms.team:443",
Please remove the `https://` from the address since it's not used in the protocol

2023-10-16 12:24 UTC, jlehtimaki commented
I'm closing this since there's no activity

2023-10-16 12:24 UTC, closed without merging